/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
/**
 *
 * @author estudiantes
 */
public class FormVenderBoletas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormVenderBoletas.class.getName());
    private FormPrincipal myP;
    /**
     * Creates new form FormVenderBoletas
     */
    public FormVenderBoletas(FormPrincipal p) {
        initComponents();
        myP = p;
        setLocationRelativeTo(null);
        botones();
        comboPartidos("Liga BetPlay Dimayor primera A");
    }
    int filas = 8;
    int columnas = 10;
    int largoBoton = 100;
    int anchoBoton = 40;    
 
    public JToggleButton [][] JTBotones = new JToggleButton[filas][columnas];
    public void botones (){
        
        int ejeX = 35;
        int ejeY = 20;

        JTBotones = new JToggleButton[filas][columnas];
        String tribuna = this.cmbTribuna.getSelectedItem().toString();

        for(int i = 0; i < filas; i++){
            for(int j = 0; j < columnas; j++){

                JTBotones[i][j] = new JToggleButton();
                JTBotones[i][j].setBounds(ejeX, ejeY, largoBoton, anchoBoton);
                JTBotones[i][j].setText(myP.getMyEstadio().sacarNumPuesto(tribuna, (i*10)+j));
                
                JTBotones[i][j].setContentAreaFilled(false);
                JTBotones[i][j].setOpaque(true);
                
                Color colorNormal = new Color(214,214,214);    
                Color colorSeleccion = new Color(0,153,51); 

                JTBotones[i][j].setBackground(colorNormal);
                
                int fila=i, col=j;  
                JTBotones[i][j].addChangeListener(e -> {
                    if (JTBotones[fila][col].isSelected()) {
                        JTBotones[fila][col].setBackground(colorSeleccion);
                    } else {
                        if (JTBotones[fila][col].isEnabled()) {
                            JTBotones[fila][col].setBackground(colorNormal);
                        }
                    }
                });
                pnlPuestos.add(JTBotones[i][j]);
                ejeX += 125;
            }
            ejeX = 35;
            ejeY += 50;
        }
    }
    public void comboPartidos(String torneo){
        cmbPartido.removeAllItems();
        if(this.myP.getMyEstadio().cantidadPartidosTorneo(torneo)==0){
            cmbPartido.addItem("No hay partidos programados");
        }else{
            for(int i = 0; i<this.myP.getMyEstadio().cantidadPartidosTorneo(torneo);i++){
                cmbPartido.addItem(myP.getMyEstadio().darFormatoPartido(i,torneo));
            }
        }
    }
   public void bloquearPuestos(ArrayList<String> puestos){
       for(String p : puestos){
            for(int i = 0; i < filas; i++){
                for(int j = 0; j < columnas; j++){
                    if(this.JTBotones[i][j].getText().equals(p)){
                        JTBotones[i][j].setBackground(Color.RED);
                        JTBotones[i][j].setEnabled(false);
                    }
                }
            } 
       }
       
   }
    public void cargarBotonesDelPartido(String torneo, int idPartido) {
        pnlPuestos.removeAll();   
        pnlPuestos.revalidate();
        pnlPuestos.repaint();
        botones();
        ArrayList<String> vendidos = myP.getMyEstadio().puestosPartido(torneo, idPartido);
        bloquearPuestos(vendidos);
    }
    public void actualizarPuestos(String torneo){
        botones();
        Object selectedItem = cmbPartido.getSelectedItem();
        if (selectedItem != null) {
            String partido = selectedItem.toString();

            if (!partido.equals("No hay partidos programados")) {
                    String[] cadenaPartidoSeparada = partido.split("\\.");
                    int idPartido = Integer.parseInt(cadenaPartidoSeparada[0]);
                    cargarBotonesDelPartido(torneo, idPartido);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTorneo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comprarBoleta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbTribuna = new javax.swing.JComboBox<>();
        pnlPuestos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbPartido = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Venta de Boletas");

        jLabel2.setText("Torneo");

        cmbTorneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liga BetPlay Dimayor primera A", "La primera B", "CONMEBOL Libertadores", "CONMEBOL Sudamericana" }));
        cmbTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTorneoActionPerformed(evt);
            }
        });

        jLabel3.setText("Documento Aficionado:");

        jLabel5.setText("Puesto");

        comprarBoleta.setText("Compar Boleta");
        comprarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBoletaActionPerformed(evt);
            }
        });

        jLabel6.setText("PARTIDOS DISPONIBLES");

        jLabel7.setText("Tribuna:");

        cmbTribuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Norte", "Sur", "Oriente", "Occidente" }));
        cmbTribuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTribunaActionPerformed(evt);
            }
        });

        pnlPuestos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlPuestosLayout = new javax.swing.GroupLayout(pnlPuestos);
        pnlPuestos.setLayout(pnlPuestosLayout);
        pnlPuestosLayout.setHorizontalGroup(
            pnlPuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1299, Short.MAX_VALUE)
        );
        pnlPuestosLayout.setVerticalGroup(
            pnlPuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel4.setText("Puesto Seleccionado");

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel8.setText("Puesto Ocupado");

        cmbPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPartidoActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(214, 214, 214));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel9.setText("Puesto Libre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(66, 66, 66)
                        .addComponent(cmbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comprarBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(cmbTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(pnlPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comprarBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel9)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTorneoActionPerformed
        String torneo = this.cmbTorneo.getSelectedItem().toString();
        pnlPuestos.removeAll();
        pnlPuestos.revalidate();
        pnlPuestos.repaint();
        comboPartidos(torneo);
        actualizarPuestos(torneo);
    }//GEN-LAST:event_cmbTorneoActionPerformed

    private void cmbTribunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTribunaActionPerformed
        pnlPuestos.removeAll();
        pnlPuestos.revalidate();
        pnlPuestos.repaint();
        String torneo = this.cmbTorneo.getSelectedItem().toString();
        actualizarPuestos(torneo);
    }//GEN-LAST:event_cmbTribunaActionPerformed

    private void comprarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBoletaActionPerformed
        String torneo = this.cmbTorneo.getSelectedItem().toString();
        int cedula = Integer.parseInt(this.txtCedula.getText());
        String partido = this.cmbPartido.getSelectedItem().toString();
        ArrayList<String> puestosSeleccionados = new ArrayList<>();

        for (Component c : pnlPuestos.getComponents()) {
            if (c instanceof JToggleButton btn) {
                if (btn.isSelected()) {
                    puestosSeleccionados.add(btn.getText());
                }
            }
        }
        String cad = this.myP.getMyEstadio().ventaBoleta(torneo, cedula, partido, puestosSeleccionados);
        JOptionPane.showMessageDialog(this, cad);
        String[] cadenaPartidoSeparada = partido.split("\\."); 
        int idPartido = Integer.parseInt(cadenaPartidoSeparada[0]);
        cargarBotonesDelPartido(torneo, idPartido);
    }//GEN-LAST:event_comprarBoletaActionPerformed

    private void cmbPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPartidoActionPerformed
    if (cmbPartido.getSelectedItem() != null) { 
        String torneo = this.cmbTorneo.getSelectedItem().toString();
        String partido = cmbPartido.getSelectedItem().toString();
        if (!partido.equals("No hay partidos programados")) {
            String[] cadenaPartidoSeparada = partido.split("\\.");  
            int idPartido = Integer.parseInt(cadenaPartidoSeparada[0]);
            cargarBotonesDelPartido(torneo, idPartido);
        }
    }
    }//GEN-LAST:event_cmbPartidoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPartido;
    private javax.swing.JComboBox<String> cmbTorneo;
    private javax.swing.JComboBox<String> cmbTribuna;
    private javax.swing.JButton comprarBoleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlPuestos;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
